---
name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '9.12.2'
          cabal-version: '3.14.2.0'

      - name: Cache Cabal store
        uses: actions/cache@v4
        env:
          cache-name: cache-cabal
        with:
          path: $HOME/.cabal/store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ts-data.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Cache dist-newstyle
        uses: actions/cache@v4
        env:
          cache-name: cache-dist-newstyle
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/**/*.hs','lib/**/*.hs',  'test/**/*.hs', 'ts-data.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies, if necessary
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Debug output
        run: find .. ~ \( -name .cabal -o -name store -o -name "ghc-9.12.2*" \) -ls

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks --disable-documentation all

      - name: Run tests
        run: cabal test all
