---
# yamllint disable rule:line-length
name: Haskell CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '9.12.2'
          cabal-version: '3.14.2.0'

      - name: Cache Cabal store
        uses: actions/cache@v4
        env:
          cache-name: cache-cabal
        with:
          path: cabal-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ts-data.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Cache dist-newstyle
        uses: actions/cache@v4
        env:
          cache-name: cache-dist-newstyle
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/**/*.hs','lib/**/*.hs', 'test/**/*.hs', 'ts-data.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: |
          cabal --store-dir $PWD/cabal-store update
          cabal --store-dir $PWD/cabal-store build --only-dependencies \
            --enable-benchmarks

      - name: Run tests with coverage
        run: cabal --store-dir $PWD/cabal-store test --enable-coverage

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v4
        with:
          target: cabal:ts-data-test
          src: app,lib
          excludes: Main,System.AppTestCase,System.Persistence,Unit.Libs.Download.MealyMachine,Unit.Libs.Download.Parsers,Unit.Libs.Download.Time,Unit.Libs.Serve,Unit.Libs.Types.ClubPerformanceReportDescriptor,Unit.Common.Sorting
          mix: dist-newstyle/build/x86_64-linux/ghc-9.12.2/ts-data-0.1.0.0/build/extra-compilation-artifacts/hpc/vanilla/mix

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Install hlint
        run: cabal --store-dir $PWD/cabal-store install hlint

      - name: Run hlint
        run: hlint app lib test

      - name: Install fourmolu
        run: cabal --store-dir $PWD/cabal-store install fourmolu

      - name: Run fourmolu check
        run: |
          find app lib test -name '*.hs' -print | xargs fourmolu --mode check

      - name: Build
        run: cabal --store-dir $PWD/cabal-store build --disable-documentation all

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_HOST }} >> ~/.ssh/known_hosts

      - name: Copy executables
        run: |
          rsync -azve "ssh -i ~/.ssh/id_ed25519" \
            dist-newstyle/build/x86_64-linux/ghc-9.12.2/ts-data-0.1.0.0/x/download-reports/build/download-reports/download-reports \
            dist-newstyle/build/x86_64-linux/ghc-9.12.2/ts-data-0.1.0.0/x/gendocs/build/gendocs/gendocs \
            dist-newstyle/build/x86_64-linux/ghc-9.12.2/ts-data-0.1.0.0/x/server/build/server/server \
            ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:

      - name: Restart server
        run: |
          ssh ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} \
              'sudo systemctl restart ts-data'

      - name: Generate OpenAPI documentation
        run: |
          ssh ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} \
              './gendocs -o static/openapi.json'
