---
name: Debug Cabal Paths

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug-cabal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haskell (GHC + Cabal)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.12.2'
          cabal-version: '3.14.2.0'

      - name: Debug Cabal paths
        run: |
          cabal update
          echo "HOME=$HOME"
          cabal user-config diff || echo "(no user config)"
          echo "store-dir (from help):"
          cabal --help | grep store-dir || true
          echo "Listing ~/.cabal:"
          find "$HOME/.cabal" -type d || true
